Made plugin manager URL configurable (#95)
Useful for local mirrors / adding additional URL parameters.

Enhancement: resolves #93

diff --git a/templates/install-intellij-plugins.sh.j2 b/templates/install-intellij-plugins.sh.j2
--- a/templates/install-intellij-plugins.sh.j2
+++ b/templates/install-intellij-plugins.sh.j2
@@ -3,6 +3,7 @@
 download_dir={{ intellij_download_dir }}
 intellij_home={{ intellij_install_dir }}
 intellij_user_dir={{ intellij_user_dir }}
+plugin_manager_url={{ intellij_plugin_manager_url }}
 
 resources_jar=$intellij_home/lib/resources.jar
 info_xml=idea/IdeaApplicationInfo.xml
@@ -19,13 +20,14 @@ declare -A plugin_file_map
 
 download_plugin() {
     plugin_id=$1
-    plugin_manager_url='https://plugins.jetbrains.com/pluginManager/'
-    plugin_manager_plugin_url="$plugin_manager_url?action=download&build=$buid_number"
 
     for i in {1..3}
     do
-        headers=$(curl --silent --data-urlencode "id=$plugin_id" --get \
-            --head "$plugin_manager_plugin_url" | dos2unix)
+        headers=$(curl --silent --get --head \
+            --data-urlencode 'action=download' \
+            --data-urlencode "build=$buid_number" \
+            --data-urlencode "id=$plugin_id" \
+            "$plugin_manager_url" | dos2unix)
         if [ $? -eq 0 ]; then
             status_code=$(echo "$headers" | sed -n 1p | awk '{ print $2 }') || return 2
             if [ $status_code -eq 404 ]; then
@@ -39,7 +41,7 @@ download_plugin() {
         sleep 5s
     done
     if [ $? -ne 0 ]; then
-        echo "Error querying plugin details from $plugin_manager_plugin_url" >&2
+        echo "Error querying plugin details from $plugin_manager_url with build=$buid_number and id=$plugin_id" >&2
         return 2
     fi
 
